compatibility_date = "2025-03-30"
name = "srs"
workers_dev = false
preview_urls = false

[assets]
directory = "./public/"

[[routes]]
custom_domain = true
pattern = "srs.chaimi.cc"

[build]
command = "go run ./src -c ./config.json"
